import { getMigrationTarget, getTargetFamily } from './migrationTargets'

const CODEGEN_PHASES = [
  { id: 'scaffold', label: 'Project scaffold', detail: 'Root structure, build config, README' },
  { id: 'contracts', label: 'API contracts', detail: 'OpenAPI / DTOs from legacy boundaries' },
  { id: 'modules', label: 'Domain modules', detail: 'Vertical slices from migration backlog' },
  { id: 'integration', label: 'Strangler facade', detail: 'Legacy adapters & feature flags' },
  { id: 'tests', label: 'Tests & harness', detail: 'Unit stubs and harness task definitions' },
]

function slugify(label) {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function modulePackageName(label) {
  return slugify(label).replace(/-/g, '')
}

function pascalCase(slug) {
  return slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

function generateSpringScaffold(scan, blueprint, opts) {
  const base = opts.packageBase ?? 'com.horizon.migration'
  const project = slugify(scan.sourceLabel?.split('(')[0]?.trim() ?? 'migration')
  const files = []

  files.push({
    path: 'pom.xml',
    phase: 'scaffold',
    module: 'root',
    content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${base}</groupId>
  <artifactId>${project}</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>${scan.sourceLabel} — Migration</name>
  <modules>
${blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b) => `    <module>${slugify(b.targetModule)}</module>`).join('\n')}
    <module>migration-facade</module>
  </modules>
  <properties>
    <java.version>21</java.version>
    <spring-boot.version>3.4.0</spring-boot.version>
  </properties>
</project>`,
  })

  files.push({
    path: 'README.md',
    phase: 'scaffold',
    module: 'root',
    content: `# ${scan.sourceLabel} → ${blueprint.targetLabel}

Generated by TCS Reverse Engineering Studio.

## Source
- **Legacy:** ${scan.stats.languages.join(', ')} (${scan.stats.totalFiles} files)
- **Domain:** ${scan.stats.domain}
- **Readiness:** ${scan.migration.score}/100 (${scan.migration.readiness})

## Target
${blueprint.targetDescription}

## Migration phases
${blueprint.phases.map((p, i) => `${i + 1}. **${p.title}** — ${p.duration}`).join('\n')}

## Next steps
1. Run \`mvn verify\` in each service module
2. Import harness tasks from \`harness/tasks.json\`
3. Wire strangler facade routes in \`migration-facade\`
4. Governance sign-off before cutover
`,
  })

  return files
}

function generateSpringContracts(scan, blueprint, opts) {
  const base = opts.packageBase ?? 'com.horizon.migration'
  const files = []

  files.push({
    path: 'contracts/openapi/migration-api.yaml',
    phase: 'contracts',
    module: 'contracts',
    content: `openapi: 3.0.3
info:
  title: ${scan.sourceLabel} Migration API
  version: 0.1.0
  description: Strangler facade contracts derived from legacy ${scan.stats.domain} modules
paths:
${blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b) => {
  const path = `/${slugify(b.module)}`
  return `  ${path}/execute:
    post:
      summary: Migrate ${b.module} operation
      operationId: execute${pascalCase(slugify(b.module))}
      tags: [${slugify(b.module)}]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/${pascalCase(slugify(b.module))}Request'
      responses:
        '200':
          description: Migrated response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/${pascalCase(slugify(b.module))}Response'`
}).join('\n')}
components:
  schemas:
${blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b) => {
  const name = pascalCase(slugify(b.module))
  return `    ${name}Request:
      type: object
      description: Translated from legacy ${b.module} (${b.fileCount} files)
      properties:
        correlationId:
          type: string
        payload:
          type: object
    ${name}Response:
      type: object
      properties:
        status:
          type: string
          enum: [SUCCESS, PARTIAL, LEGACY_FALLBACK]
        result:
          type: object`
}).join('\n')}
`,
  })

  files.push({
    path: `src/main/java/${base.replace(/\./g, '/')}/contracts/LegacyModuleMapping.java`,
    phase: 'contracts',
    module: 'contracts',
    content: `package ${base}.contracts;

import java.util.Map;

/** Maps legacy modules to Spring service boundaries (generated). */
public final class LegacyModuleMapping {
  private LegacyModuleMapping() {}

  public static final Map<String, String> MODULE_TO_SERVICE = Map.of(
${blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b) => `      "${b.module}", "${slugify(b.targetModule)}"`).join(',\n')}
  );
}
`,
  })

  return files
}

function generateSpringModule(scan, backlogItem, blueprint, opts) {
  const base = opts.packageBase ?? 'com.horizon.migration'
  const slug = slugify(backlogItem.targetModule)
  const pkg = `${base}.${modulePackageName(backlogItem.module)}`
  const cls = pascalCase(slugify(backlogItem.module))
  const domain = scan.stats.domain ?? 'general'

  return [
    {
      path: `${slug}/src/main/java/${pkg.replace(/\./g, '/')}/${cls}Application.java`,
      phase: 'modules',
      module: backlogItem.module,
      content: `package ${pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ${cls}Application {
  public static void main(String[] args) {
    SpringApplication.run(${cls}Application.class, args);
  }
}
`,
    },
    {
      path: `${slug}/src/main/java/${pkg.replace(/\./g, '/')}/api/${cls}Controller.java`,
      phase: 'modules',
      module: backlogItem.module,
      content: `package ${pkg}.api;

import ${pkg}.domain.${cls}Request;
import ${pkg}.domain.${cls}Response;
import ${pkg}.service.${cls}Service;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/${slugify(backlogItem.module)}")
public class ${cls}Controller {
  private final ${cls}Service service;

  public ${cls}Controller(${cls}Service service) {
    this.service = service;
  }

  @PostMapping("/execute")
  public ${cls}Response execute(@RequestBody ${cls}Request request) {
    return service.execute(request);
  }
}
`,
    },
    {
      path: `${slug}/src/main/java/${pkg.replace(/\./g, '/')}/domain/${cls}Request.java`,
      phase: 'modules',
      module: backlogItem.module,
      content: `package ${pkg}.domain;

/** DTO translated from legacy ${backlogItem.module} (${domain}). */
public record ${cls}Request(String correlationId, Object payload) {}
`,
    },
    {
      path: `${slug}/src/main/java/${pkg.replace(/\./g, '/')}/domain/${cls}Response.java`,
      phase: 'modules',
      module: backlogItem.module,
      content: `package ${pkg}.domain;

public record ${cls}Response(String status, Object result) {
  public static ${cls}Response success(Object result) {
    return new ${cls}Response("SUCCESS", result);
  }
}
`,
    },
    {
      path: `${slug}/src/main/java/${pkg.replace(/\./g, '/')}/service/${cls}Service.java`,
      phase: 'modules',
      module: backlogItem.module,
      content: `package ${pkg}.service;

import ${pkg}.domain.${cls}Request;
import ${pkg}.domain.${cls}Response;
import org.springframework.stereotype.Service;

/**
 * Migrated from legacy ${backlogItem.module}.
 * Story: ${backlogItem.story}
 */
@Service
public class ${cls}Service {
  public ${cls}Response execute(${cls}Request request) {
    // TODO: port business rules from ${backlogItem.module}
    // Harness: validate against legacy parity tests
    return ${cls}Response.success(
        java.util.Map.of(
            "module", "${backlogItem.module}",
            "target", "${backlogItem.targetModule}",
            "correlationId", request.correlationId()
        )
    );
  }
}
`,
    },
  ]
}

function generateSpringIntegration(scan, blueprint, opts) {
  const base = opts.packageBase ?? 'com.horizon.migration'
  const files = []

  files.push({
    path: 'migration-facade/src/main/java/com/horizon/migration/facade/StranglerRouter.java',
    phase: 'integration',
    module: 'facade',
    content: `package ${base}.facade;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.util.Map;

/**
 * Routes traffic between legacy system and ${blueprint.targetLabel} services.
 * Enable progressive cutover via feature flags.
 */
@Component
public class StranglerRouter {
  @Value("\${migration.legacy.base-url:http://mainframe-gateway.internal}")
  private String legacyBaseUrl;

  private final Map<String, String> serviceRoutes = Map.of(
${blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b, idx) => `      "${b.module}", "http://localhost:808${idx + 1}/${slugify(b.module)}"`).join(',\n')}
  );

  public String route(String legacyModule) {
    return serviceRoutes.getOrDefault(legacyModule, legacyBaseUrl + "/" + legacyModule);
  }
}
`,
  })

  files.push({
    path: 'migration-facade/src/main/resources/application.yml',
    phase: 'integration',
    module: 'facade',
    content: `migration:
  source: ${JSON.stringify(scan.sourceLabel)}
  target: ${blueprint.targetLabel}
  readiness: ${scan.migration.score}
  feature-flags:
    enable-pasauth: false
    enable-clmmain: false
  legacy:
    base-url: http://mainframe-gateway.internal
`,
  })

  return files
}

function generateSpringTests(scan, blueprint, opts) {
  const base = opts.packageBase ?? 'com.horizon.migration'
  const files = []

  blueprint.backlog.slice(0, opts.moduleLimit ?? 3).forEach((b) => {
    const slug = slugify(b.targetModule)
    const cls = pascalCase(slugify(b.module))
    const pkg = `${base}.${modulePackageName(b.module)}`
    files.push({
      path: `${slug}/src/test/java/${pkg.replace(/\./g, '/')}/service/${cls}ServiceTest.java`,
      phase: 'tests',
      module: b.module,
      content: `package ${pkg}.service;

import ${pkg}.domain.${cls}Request;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ${cls}ServiceTest {
  @Test
  void execute_returnsSuccessForValidRequest() {
    var service = new ${cls}Service();
    var response = service.execute(new ${cls}Request("test-corr-1", java.util.Map.of()));
    assertEquals("SUCCESS", response.status());
  }
}
`,
    })
  })

  files.push({
    path: 'harness/tasks.json',
    phase: 'tests',
    module: 'harness',
    content: JSON.stringify(
      {
        workspace: scan.sourceLabel,
        targetStack: blueprint.targetLabel,
        tasks: blueprint.backlog.slice(0, opts.moduleLimit ?? 3).map((b) => ({
          id: `harness-${slugify(b.module)}`,
          module: b.module,
          targetModule: b.targetModule,
          category: b.module.match(/PASAUTH|ELIG/i) ? 'ad' : b.module.match(/CLM/i) ? 'qe' : 'ams',
          task: `Validate ${b.targetModule} parity against legacy ${b.module} — ${b.story}`,
          harnessRoute: '/harness',
        })),
      },
      null,
      2
    ),
  })

  return files
}

function generateReactModule(scan, backlogItem, blueprint, opts) {
  const slug = slugify(backlogItem.module)
  const cls = pascalCase(slug)
  const files = []

  files.push({
    path: `src/features/${slug}/${cls}Page.tsx`,
    phase: 'modules',
    module: backlogItem.module,
    content: `import { useState } from 'react'
import { ${cls}Client } from './api/${cls}Client'

/** Migrated UI for legacy ${backlogItem.module} → ${backlogItem.targetModule} */
export function ${cls}Page() {
  const [result, setResult] = useState<unknown>(null)
  const client = new ${cls}Client()

  const handleExecute = async () => {
    const res = await client.execute({ correlationId: crypto.randomUUID() })
    setResult(res)
  }

  return (
    <div className="p-6">
      <h1 className="text-lg font-semibold">${backlogItem.module}</h1>
      <p className="text-sm text-muted">${backlogItem.story}</p>
      <button type="button" onClick={handleExecute} className="mt-4 px-4 py-2 rounded-lg border">
        Execute migrated flow
      </button>
      {result && <pre className="mt-4 text-xs">{JSON.stringify(result, null, 2)}</pre>}
    </div>
  )
}
`,
  })

  files.push({
    path: `src/features/${slug}/api/${cls}Client.ts`,
    phase: 'modules',
    module: backlogItem.module,
    content: `export class ${cls}Client {
  async execute(body: { correlationId: string; payload?: unknown }) {
    const res = await fetch('/api/v1/${slug}/execute', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    return res.json()
  }
}
`,
  })

  return files
}

function generateFrontendScaffold(scan, blueprint, target) {
  const name = slugify(scan.sourceLabel?.split('(')[0]?.trim() ?? 'migration')
  const ext = target.id === 'nextjs' ? 'next' : target.id
  return [
    {
      path: 'package.json',
      phase: 'scaffold',
      module: 'root',
      content: JSON.stringify(
        {
          name,
          version: '0.1.0',
          private: true,
          scripts: {
            dev: target.id === 'nextjs' ? 'next dev' : 'vite',
            build: target.id === 'angular' ? 'ng build' : 'tsc && vite build',
            test: 'vitest',
          },
          dependencies: { framework: target.label },
        },
        null,
        2
      ),
    },
    {
      path: 'README.md',
      phase: 'scaffold',
      module: 'root',
      content: `# ${scan.sourceLabel} → ${target.label}\n\nStack: ${target.techStack.join(', ')}\n\nGenerated under \`src/\`.\n`,
    },
    {
      path: `tooling/${ext}-config.json`,
      phase: 'scaffold',
      module: 'root',
      content: JSON.stringify({ target: target.id, tooling: target.tooling }, null, 2),
    },
  ]
}

function generateDotNetScaffold(scan, blueprint, opts) {
  const project = slugify(scan.sourceLabel?.split('(')[0]?.trim() ?? 'migration')
  return [
    {
      path: `${project}.sln`,
      phase: 'scaffold',
      module: 'root',
      content: `# ${scan.sourceLabel} → ${blueprint.targetLabel}\n`,
    },
    {
      path: 'src/Migration.Host/Migration.Host.csproj',
      phase: 'scaffold',
      module: 'root',
      content: `<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>`,
    },
    {
      path: 'README.md',
      phase: 'scaffold',
      module: 'root',
      content: `# ${scan.sourceLabel} → ${blueprint.targetLabel}\n\n.NET 8 vertical slices per migration backlog.\n`,
    },
  ]
}

function generateDotNetModule(scan, item, blueprint) {
  const cls = pascalCase(slugify(item.module))
  const ns = `Tcs.Migration.${cls}`
  const slug = slugify(item.targetModule)
  return [
    {
      path: `src/${cls}/${cls}Endpoints.cs`,
      phase: 'modules',
      module: item.module,
      content: `using Microsoft.AspNetCore.Mvc;

namespace ${ns};

public static class ${cls}Endpoints {
  public static void Map(WebApplication app) {
    app.MapPost("/api/v1/${slugify(item.module)}/execute", async (${cls}Request req) =>
      Results.Ok(new ${cls}Response("SUCCESS", new { req.CorrelationId, module = "${item.module}" }))
    );
  }
}

public record ${cls}Request(string CorrelationId, object? Payload);
public record ${cls}Response(string Status, object Result);
`,
    },
  ]
}

function generateFastApiScaffold(scan, blueprint) {
  return [
    {
      path: 'pyproject.toml',
      phase: 'scaffold',
      module: 'root',
      content: `[project]
name = "${slugify(scan.sourceLabel?.split('(')[0] ?? 'migration')}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["fastapi>=0.115", "uvicorn[standard]>=0.32", "pydantic>=2.0"]
`,
    },
    {
      path: 'README.md',
      phase: 'scaffold',
      module: 'root',
      content: `# ${scan.sourceLabel} → ${blueprint.targetLabel}\n\n\`uvicorn app.main:app --reload\`\n`,
    },
    {
      path: 'app/main.py',
      phase: 'scaffold',
      module: 'root',
      content: `from fastapi import FastAPI

app = FastAPI(title="${scan.sourceLabel} Migration")

@app.get("/health")
def health():
    return {"status": "ok"}
`,
    },
  ]
}

function generateFastApiModule(item) {
  const slug = slugify(item.module)
  const cls = pascalCase(slug)
  return [
    {
      path: `app/routers/${slug}_router.py`,
      phase: 'modules',
      module: item.module,
      content: `from pydantic import BaseModel
from fastapi import APIRouter

router = APIRouter(prefix="/api/v1/${slug}", tags=["${slug}"])

class ${cls}Request(BaseModel):
    correlation_id: str
    payload: dict | None = None

class ${cls}Response(BaseModel):
    status: str
    result: dict

@router.post("/execute", response_model=${cls}Response)
async def execute(req: ${cls}Request):
    """Migrated from legacy ${item.module} → ${item.targetModule}"""
    return ${cls}Response(status="SUCCESS", result={"module": "${item.module}", "correlation_id": req.correlation_id})
`,
    },
  ]
}

function generateAngularModule(item) {
  const cls = pascalCase(slugify(item.module))
  const slug = slugify(item.module)
  return [
    {
      path: `src/app/features/${slug}/${slug}.component.ts`,
      phase: 'modules',
      module: item.module,
      content: `import { Component } from '@angular/core';
import { ${cls}Service } from './${slug}.service';

@Component({
  selector: 'app-${slug}',
  standalone: true,
  template: \`<section><h2>${item.module}</h2><button (click)="run()">Execute</button></section>\`,
})
export class ${cls}Component {
  constructor(private svc: ${cls}Service) {}
  run() { this.svc.execute(crypto.randomUUID()).subscribe(); }
}
`,
    },
    {
      path: `src/app/features/${slug}/${slug}.service.ts`,
      phase: 'modules',
      module: item.module,
      content: `import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({ providedIn: 'root' })
export class ${cls}Service {
  constructor(private http: HttpClient) {}
  execute(correlationId: string) {
    return this.http.post('/api/v1/${slug}/execute', { correlationId });
  }
}
`,
    },
  ]
}

function generateVueModule(item) {
  const cls = pascalCase(slugify(item.module))
  const slug = slugify(item.module)
  return [
    {
      path: `src/views/${cls}View.vue`,
      phase: 'modules',
      module: item.module,
      content: `<script setup lang="ts">
import { ref } from 'vue'
import { use${cls}Api } from '../composables/use${cls}Api'

const result = ref<unknown>(null)
const api = use${cls}Api()

async function run() {
  result.value = await api.execute(crypto.randomUUID())
}
</script>

<template>
  <section class="p-6">
    <h2>${item.module}</h2>
    <p class="text-sm opacity-70">${item.story}</p>
    <button @click="run">Execute migrated flow</button>
    <pre v-if="result">{{ result }}</pre>
  </section>
</template>
`,
    },
    {
      path: `src/composables/use${cls}Api.ts`,
      phase: 'modules',
      module: item.module,
      content: `export function use${cls}Api() {
  return {
    async execute(correlationId: string) {
      const res = await fetch('/api/v1/${slug}/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ correlationId }),
      })
      return res.json()
    },
  }
}
`,
    },
  ]
}

function generateNextModule(item) {
  const slug = slugify(item.module)
  const cls = pascalCase(slug)
  return [
    {
      path: `app/${slug}/page.tsx`,
      phase: 'modules',
      module: item.module,
      content: `'use client'
import { useState } from 'react'

export default function ${cls}Page() {
  const [result, setResult] = useState<unknown>(null)
  async function run() {
    const res = await fetch('/api/v1/${slug}/execute', { method: 'POST', body: JSON.stringify({ correlationId: crypto.randomUUID() }) })
    setResult(await res.json())
  }
  return (
    <main className="p-6">
      <h1>${item.module}</h1>
      <button onClick={run}>Execute</button>
      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}
    </main>
  )
}
`,
    },
    {
      path: `app/api/v1/${slug}/execute/route.ts`,
      phase: 'modules',
      module: item.module,
      content: `import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  const body = await req.json()
  return NextResponse.json({ status: 'SUCCESS', module: '${item.module}', correlationId: body.correlationId })
}
`,
    },
  ]
}

function generateFrontendModule(scan, item, blueprint, target) {
  switch (target.id) {
    case 'angular':
      return generateAngularModule(item)
    case 'vue':
      return generateVueModule(item)
    case 'nextjs':
      return generateNextModule(item)
    default:
      return generateReactModule(scan, item, blueprint, {})
  }
}

function generateHarnessTasks(scan, blueprint, backlogSlice, targetLabel) {
  return {
    path: 'harness/tasks.json',
    phase: 'tests',
    module: 'harness',
    content: JSON.stringify(
      {
        workspace: scan.sourceLabel,
        targetStack: targetLabel,
        tasks: backlogSlice.map((b) => ({
          id: `harness-${slugify(b.module)}`,
          module: b.module,
          targetModule: b.targetModule,
          task: `Validate ${b.targetModule} parity against legacy ${b.module}`,
          harnessRoute: '/harness',
        })),
      },
      null,
      2
    ),
  }
}

function generateReactScaffold(scan, blueprint, target) {
  return generateFrontendScaffold(scan, blueprint, target)
}

/**
 * Generate migration code artifacts from scan + blueprint.
 * @returns {{ phases, files, summary, generatedAt, options }}
 */
export function generateMigrationCode(scan, blueprint, options = {}) {
  const targetId = options.targetStack ?? blueprint.targetStack
  const target = getMigrationTarget(targetId)
  const family = getTargetFamily(targetId)
  const effectiveBlueprint = {
    ...blueprint,
    targetStack: target.id,
    targetLabel: target.label,
    targetDescription: target.description,
  }

  const scope = options.scope ?? 'p0'
  const moduleLimit = scope === 'scaffold' ? 0 : scope === 'p0' ? 2 : blueprint.backlog.length
  const opts = {
    packageBase: options.packageBase ?? 'com.horizon.migration',
    moduleLimit,
    scope,
    targetStack: target.id,
  }

  const backlogSlice = blueprint.backlog.slice(0, moduleLimit)
  let files = []

  if (family === 'jvm') {
    files.push(...generateSpringScaffold(scan, effectiveBlueprint, opts))
    files.push(...generateSpringContracts(scan, effectiveBlueprint, opts))
    backlogSlice.forEach((item) => files.push(...generateSpringModule(scan, item, effectiveBlueprint, opts)))
    if (moduleLimit > 0) {
      files.push(...generateSpringIntegration(scan, effectiveBlueprint, opts))
      files.push(...generateSpringTests(scan, effectiveBlueprint, opts))
    }
  } else if (family === 'dotnet') {
    files.push(...generateDotNetScaffold(scan, effectiveBlueprint, opts))
    files.push(...generateSpringContracts(scan, effectiveBlueprint, opts))
    backlogSlice.forEach((item) => files.push(...generateDotNetModule(scan, item, effectiveBlueprint)))
    if (moduleLimit > 0) files.push(generateHarnessTasks(scan, effectiveBlueprint, backlogSlice, target.label))
  } else if (family === 'python') {
    files.push(...generateFastApiScaffold(scan, effectiveBlueprint))
    backlogSlice.forEach((item) => files.push(...generateFastApiModule(item)))
    if (moduleLimit > 0) files.push(generateHarnessTasks(scan, effectiveBlueprint, backlogSlice, target.label))
  } else {
    files.push(...generateFrontendScaffold(scan, effectiveBlueprint, target))
    files.push(...generateSpringContracts(scan, effectiveBlueprint, opts))
    backlogSlice.forEach((item) => files.push(...generateFrontendModule(scan, item, effectiveBlueprint, target)))
    if (moduleLimit > 0) files.push(generateHarnessTasks(scan, effectiveBlueprint, backlogSlice, target.label))
  }

  const phases = CODEGEN_PHASES.map((p) => ({
    ...p,
    status: files.some((f) => f.phase === p.id) ? 'complete' : moduleLimit === 0 && p.id !== 'scaffold' ? 'skipped' : 'pending',
    fileCount: files.filter((f) => f.phase === p.id).length,
  }))

  return {
    scanId: scan.id,
    targetStack: target.id,
    blueprintTarget: target.label,
    generatedAt: new Date().toISOString(),
    phases: CODEGEN_PHASES,
    phaseResults: phases,
    files,
    options: opts,
    summary: `Generated ${files.length} files across ${phases.filter((p) => p.fileCount > 0).length} phases for ${backlogSlice.length} module(s) → ${target.label}`,
  }
}

export function getCodegenPhases() {
  return CODEGEN_PHASES
}

export function buildCodeBundleExport(result) {
  const header = `# TCS Migration Code Bundle
# Scan: ${result.scanId}
# Target: ${result.blueprintTarget}
# Generated: ${result.generatedAt}
# Files: ${result.files.length}

`
  const body = result.files
    .map((f) => `\n${'='.repeat(60)}\nFILE: ${f.path}\nPHASE: ${f.phase} | MODULE: ${f.module}\n${'='.repeat(60)}\n${f.content}`)
    .join('\n')
  return header + body
}

export { CODEGEN_PHASES }
