-- Claims adjudication DB2 schema (legacy)
CREATE TABLE CLAIM_HEADER (
  CLM_NUMBER      VARCHAR(15) NOT NULL PRIMARY KEY,
  MEMBER_ID       VARCHAR(12) NOT NULL,
  SERVICE_DATE    DATE,
  PROC_CODE       VARCHAR(5),
  BILLED_AMT      DECIMAL(11,2),
  PAID_AMT        DECIMAL(11,2),
  STATUS          CHAR(2),
  PRIOR_AUTH_NUM  VARCHAR(12)
);

CREATE TABLE MEMBER_ELIGIBILITY (
  MEMBER_ID       VARCHAR(12) NOT NULL PRIMARY KEY,
  EFFECT_DATE     DATE,
  TERM_DATE       DATE,
  COVERAGE_TYPE   CHAR(3),
  HIPAA_FLAG      CHAR(1)
);

CREATE INDEX IDX_CLAIM_MEMBER ON CLAIM_HEADER(MEMBER_ID);
